package fr.utbm.formationlo54.model;
// Generated 1 mai 2020 � 14:42:38 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mysession generated by hbm2java
 */
public class Mysession  implements java.io.Serializable {


     private Long sesNumero;
     private long locIentifiant;
     private Date sesDateDebut;
     private Date sesDateFin;

    public Mysession() {
    }

    public Mysession(long locIentifiant, Date sesDateDebut, Date sesDateFin) {
       this.locIentifiant = locIentifiant;
       this.sesDateDebut = sesDateDebut;
       this.sesDateFin = sesDateFin;
    }
   
    public Long getSesNumero() {
        return this.sesNumero;
    }
    
    public void setSesNumero(Long sesNumero) {
        this.sesNumero = sesNumero;
    }
    public long getLocIentifiant() {
        return this.locIentifiant;
    }
    
    public void setLocIentifiant(long locIentifiant) {
        this.locIentifiant = locIentifiant;
    }
    public Date getSesDateDebut() {
        return this.sesDateDebut;
    }
    
    public void setSesDateDebut(Date sesDateDebut) {
        this.sesDateDebut = sesDateDebut;
    }
    public Date getSesDateFin() {
        return this.sesDateFin;
    }
    
    public void setSesDateFin(Date sesDateFin) {
        this.sesDateFin = sesDateFin;
    }




}


