package fr.utbm.projet.lo54.entity;
// Generated 1 mai 2020 � 14:42:38 by Hibernate Tools 4.3.1

import fr.utbm.projet.lo54.repository.HibernateFormationDao;
import java.math.BigInteger;
import java.util.Date;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 * Formation generated by hbm2java
 */
@Named(value = "formation")
@RequestScoped
public class Formation implements java.io.Serializable {

    private Long frtNumero;
    private Long admNumero;
    private BigInteger prtCode;
    private String frtLibelle;
    private String frtDescription;
    private Date frtDateDebut;
    private Date frtDateFin;

    public Formation() {
    }

    public Formation(Long admNumero, BigInteger prtCode, String frtLibelle, String frtDescription, Date frtDateDebut, Date frtDateFin) {
        this.admNumero = admNumero;
        this.prtCode = prtCode;
        this.frtLibelle = frtLibelle;
        this.frtDescription = frtDescription;
        this.frtDateDebut = frtDateDebut;
        this.frtDateFin = frtDateFin;
    }

    public Long getFrtNumero() {
        return this.frtNumero;
    }

    public void setFrtNumero(Long frtNumero) {
        this.frtNumero = frtNumero;
    }

    public Long getAdmNumero() {
        return this.admNumero;
    }

    public void setAdmNumero(Long admNumero) {
        this.admNumero = admNumero;
    }

    public BigInteger getPrtCode() {
        return this.prtCode;
    }

    public void setPrtCode(BigInteger prtCode) {
        this.prtCode = prtCode;
    }

    public String getFrtLibelle() {
        return this.frtLibelle;
    }

    public void setFrtLibelle(String frtLibelle) {
        this.frtLibelle = frtLibelle;
    }

    public String getFrtDescription() {
        return this.frtDescription;
    }

    public void setFrtDescription(String frtDescription) {
        this.frtDescription = frtDescription;
    }

    public Date getFrtDateDebut() {
        return this.frtDateDebut;
    }

    public void setFrtDateDebut(Date frtDateDebut) {
        this.frtDateDebut = frtDateDebut;
    }

    public Date getFrtDateFin() {
        return this.frtDateFin;
    }

    public void setFrtDateFin(Date frtDateFin) {
        this.frtDateFin = frtDateFin;
    }

    public void updateFormation(int id) {
        HibernateFormationDao formaDAO = new HibernateFormationDao();
        formaDAO.updateFormation(id, 1, frtLibelle, frtDescription, 1, frtDateDebut, frtDateFin);
        for (Formation l : formaDAO.uniqueFormation(id)) {
            System.err.println(l.getFrtLibelle() + "----------------   " + l.getFrtDescription());
        }
    }

}
