package fr.utbm.projet.lo54.entity;
// Generated 1 mai 2020 � 14:42:38 by Hibernate Tools 4.3.1

/**
 * Localisation generated by hbm2java
 */
public class Localisation implements java.io.Serializable {

    private Long locIentifiant;
    private String locCity;

    public Localisation() {
    }

    public Localisation(String locCity) {
        this.locCity = locCity;
    }

    public Long getLocIentifiant() {
        return this.locIentifiant;
    }

    public void setLocIentifiant(Long locIentifiant) {
        this.locIentifiant = locIentifiant;
    }

    public String getLocCity() {
        return this.locCity;
    }

    public void setLocCity(String locCity) {
        this.locCity = locCity;
    }

}
