package fr.utbm.projet.lo54.entity;
// Generated 1 mai 2020 � 14:42:38 by Hibernate Tools 4.3.1

import java.io.Serializable;




/**
 * Subdiviser generated by hbm2java
 */
public class Subdiviser  implements Serializable {


     private SubdiviserPK id;

    public Subdiviser() {
    }

    public Subdiviser(SubdiviserPK id) {
       this.id = id;
       
    }
   
    public SubdiviserPK getId() {
        return this.id;
    }
    
    public void setId(SubdiviserPK id) {
        this.id = id;
    }




}


