package fr.utbm.projet.lo54.entity;
// Generated 1 mai 2020 � 14:42:38 by Hibernate Tools 4.3.1


import java.math.BigInteger;
import java.util.Date;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private Long utiNumero;
     private String utiNom;
     private String utiPrenom;
     private Date utiDateNaissance;
     private BigInteger utiNumeroRue;
     private String utiNomRue;
     private String utiVille;
     private String utiCodePostale;
     private String utiAdresseEmail;
     private String utiPassword;

    public Utilisateur() {
    }

	
    public Utilisateur(String utiNom, String utiPrenom, Date utiDateNaissance, String utiNomRue, String utiVille, String utiCodePostale, String utiAdresseEmail, String utiPassword) {
        this.utiNom = utiNom;
        this.utiPrenom = utiPrenom;
        this.utiDateNaissance = utiDateNaissance;
        this.utiNomRue = utiNomRue;
        this.utiVille = utiVille;
        this.utiCodePostale = utiCodePostale;
        this.utiAdresseEmail = utiAdresseEmail;
        this.utiPassword = utiPassword;
    }
    public Utilisateur(String utiNom, String utiPrenom, Date utiDateNaissance, BigInteger utiNumeroRue, String utiNomRue, String utiVille, String utiCodePostale, String utiAdresseEmail, String utiPassword) {
       this.utiNom = utiNom;
       this.utiPrenom = utiPrenom;
       this.utiDateNaissance = utiDateNaissance;
       this.utiNumeroRue = utiNumeroRue;
       this.utiNomRue = utiNomRue;
       this.utiVille = utiVille;
       this.utiCodePostale = utiCodePostale;
       this.utiAdresseEmail = utiAdresseEmail;
       this.utiPassword = utiPassword;
    }
   
    public Long getUtiNumero() {
        return this.utiNumero;
    }
    
    public void setUtiNumero(Long utiNumero) {
        this.utiNumero = utiNumero;
    }
    public String getUtiNom() {
        return this.utiNom;
    }
    
    public void setUtiNom(String utiNom) {
        this.utiNom = utiNom;
    }
    public String getUtiPrenom() {
        return this.utiPrenom;
    }
    
    public void setUtiPrenom(String utiPrenom) {
        this.utiPrenom = utiPrenom;
    }
    public Date getUtiDateNaissance() {
        return this.utiDateNaissance;
    }
    
    public void setUtiDateNaissance(Date utiDateNaissance) {
        this.utiDateNaissance = utiDateNaissance;
    }
    public BigInteger getUtiNumeroRue() {
        return this.utiNumeroRue;
    }
    
    public void setUtiNumeroRue(BigInteger utiNumeroRue) {
        this.utiNumeroRue = utiNumeroRue;
    }
    public String getUtiNomRue() {
        return this.utiNomRue;
    }
    
    public void setUtiNomRue(String utiNomRue) {
        this.utiNomRue = utiNomRue;
    }
    public String getUtiVille() {
        return this.utiVille;
    }
    
    public void setUtiVille(String utiVille) {
        this.utiVille = utiVille;
    }
    public String getUtiCodePostale() {
        return this.utiCodePostale;
    }
    
    public void setUtiCodePostale(String utiCodePostale) {
        this.utiCodePostale = utiCodePostale;
    }
    public String getUtiAdresseEmail() {
        return this.utiAdresseEmail;
    }
    
    public void setUtiAdresseEmail(String utiAdresseEmail) {
        this.utiAdresseEmail = utiAdresseEmail;
    }
    public String getUtiPassword() {
        return this.utiPassword;
    }
    
    public void setUtiPassword(String utiPassword) {
        this.utiPassword = utiPassword;
    }

}


